name: Continuous integration

on:
  pull_request:
    branches: [ master ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Download dependencies
        run: |
          sudo apt-get -y update
          curl -sS https://getcomposer.org/installer 
          php -- --install-dir=/usr/local/bin --filename=composer
      - name: Checkout current branch
        uses: actions/checkout@v2
      - name: Copy .env file
        run: cp .env.example .env
      - name: Install composer dependencies
        run: composer install
      - name: Run tests
        run: php bin/phpunit
